# Generated by Django 4.0.2 on 2022-02-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('EventID', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('EventName', models.CharField(max_length=255)),
                ('EventDate', models.DateField()),
                ('EventDescription', models.TextField(max_length=65535)),
                ('EventAvailableSlots', models.PositiveSmallIntegerField()),
                ('EventMaximumCapacity', models.PositiveSmallIntegerField()),
                ('EventTime', models.TimeField()),
            ],
        ),
    ]
