# Generated by Django 4.0.2 on 2022-02-27 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('ReservationNum', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('ReservationDate', models.DateField()),
                ('ReservationTimeSlot', models.TimeField()),
                ('ReservationNumberOfPeople', models.PositiveSmallIntegerField()),
                ('ReservationConfirmationStatus', models.BooleanField()),
                ('ReservationAttendance', models.BooleanField()),
                ('EventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.event')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.accounts')),
            ],
        ),
    ]
