# Generated by Django 4.0.4 on 2022-05-27 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_reservation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accounts',
            new_name='Account',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='EMail',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='EventDate',
            new_name='EventEndDate',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='EventTime',
            new_name='EventEndTime',
        ),
        migrations.AddField(
            model_name='event',
            name='EventStartDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='EventStartTime',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='EventStatus',
            field=models.TextField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
